name: wqaya
description: "A medical project"
publish_to: null
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: null
  flutter_svg: null
  flutter_screenutil: null
  image_picker: 

  #  device_preview:
  #  firebase_core:
  #  firebase_auth:
  #  google_sign_in:
  flutter_bloc: null
  bloc: null
  shared_preferences: null
  flutter_launcher_icons: null

  flutter_staggered_grid_view: ^0.7.0

  easy_localization:
  pin_code_fields:
  dio: ^5.8.0+1
  google_sign_in: ^6.3.0
  firebase_auth: ^5.5.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/auth_view/
    - assets/images/boarding_view/
    - assets/images/home_view/
    - assets/images/splash_view/
    - assets/locals/translations/
    - assets/images/profile_view/
  fonts:
    - family: cairoBlack
      fonts:
        - asset: fonts/Cairo/Cairo-Black.ttf

    - family: cairoBold
      fonts:
        - asset: fonts/Cairo/Cairo-Bold.ttf

    - family: cairoMedium
      fonts:
        - asset: fonts/Cairo/Cairo-Medium.ttf

    - family: cairoSemiBold
      fonts:
        - asset: fonts/Cairo/Cairo-SemiBold.ttf

    - family: cairoRegular
      fonts:
        - asset: fonts/Cairo/Cairo-Regular.ttf

    - family: cairoLight
      fonts:
        - asset: fonts/Cairo/Cairo-Light.ttf

